export type IngredientCategory =
  | 'Viandes Rouges'
  | 'Viandes Blanches'
  | 'Volailles'
  | 'Poissons et fruits de mer'
  | 'Œufs'
  | 'Charcuteries'
  | 'Légumes'
  | 'Champignons'
  | 'Féculents'
  | 'Fruits'
  | 'Céréales et Grains'
  | 'Produits Laitiers'
  | 'Épices et Condiments'
  | 'Huiles et Matières Grasses'
  | 'Sucres et Édulcorants'
  | 'Boissons'
  | 'Produits Transformés'
  | 'Produits de Boulangerie'
  | 'Légumineuses'
  | 'Chocolat'
  | 'Fromages'
  | 'Fruits à Coques'
  | 'Fruits Secs'
  | 'Boissons Alcoolisées'
  | 'Produits Fermentés';
